
spring:
  profiles:
    active: cloud
---
spring:
  profiles: dev
server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: release
server:
  port: 9102

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  eureka:
    enabled: true    